### PR TITLE
BROKERS:  Update Comment

### LINKED ISSUE #53: BROKERS: Update Comment

### PR DESCRIPTION
**Pull request by cjdutoit**
Closes #53

### CODE REVIEW

**Comment by hassanhabib** [comment]
@cjdutoit resolve conflicts please.

**Comment by ShriHumrudha** [comment]
Please wait for one PR to be merged at a time and update the rest with the latest so the difference is specific to this scope.

**Comment by ShriHumrudha** [comment]
You can proceed with this PR now.

**Comment by cjdutoit** [comment]
@ShriHumrudha thanks, have updated PR

**Pull request merged**
