### PR TITLE
CODE RUB: Brokers Update Event

### LINKED ISSUE #257: BROKERS: Update Event

### PR DESCRIPTION
**Pull request by Hassaero110**
Closes #257

### CODE REVIEW

**Comment by ElbekDeveloper** [comment]
The build is failing. Please, fix the errors and pay attention to commit message. It should contain flag such as `CODE RUB`

**Comment by cjdutoit** [comment]
@Hassaero110 please resolve branch conflicts

**Comment by cjdutoit** [comment]
@Hassaero110 can you convert this to the new convention for storage brokers.  

Please see [https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md](https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md)

**Comment by cjdutoit** [comment]
@Hassaero110 can you convert this to the new convention for storage brokers.  

Please see [https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md](https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md)

**Comment by ElbekDeveloper** [comment]
This can be closed due to inactivity

**Pull request closed without merging**
