### PR TITLE
EXPOSERS: GET All Profiles

### LINKED ISSUE #345: EXPOSERS: GET All Profiles

### PR DESCRIPTION
**Pull request by GulchexrasGithub**
Closes #345

### CODE REVIEW

**Comment by cjdutoit** [comment]
@GulchexrasGithub as there is no tests for the EXPOSERS, you will need to manually show that you have tested them.  You can use something like Postman or Swagger to tests.  Take a screenshot and paste the result directly into the comment.

**Review by cjdutoit — CHANGES_REQUESTED** [review]
Please add screenshots of your test outcomes

**Comment by GulchexrasGithub** [comment]
image

**Review by cjdutoit — APPROVED** [review]
Please add screenshots of your test outcomes

**Pull request merged**
