### PR TITLE
CODE RUB: Brokers Delete Event

### LINKED ISSUE #258: BROKERS: Delete Event

### PR DESCRIPTION
**Pull request by Hassaero110**
closes #258

### CODE REVIEW

**Comment by ElbekDeveloper** [comment]
Build is failing

**Comment by cjdutoit** [comment]
@Hassaero110 please resolve branch conflicts

**Review by cjdutoit — CHANGES_REQUESTED** [review]
@Hassaero110 can you convert this to the new convention for storage brokers.  

Please see [https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md](https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md)

**Comment by ElbekDeveloper** [comment]
This PR is not being updated. We might need to close this due to inactivity

**Comment by cjdutoit** [comment]
Work has been completed in #329 by @khusnii

**Pull request closed without merging**
